let token=localStorage.getItem("co_token")||"", me=null;
const $=s=>document.querySelector(s);
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function api(url,opt={}){opt.headers={"Content-Type":"application/json",...(opt.headers||{})};if(token)opt.headers.Authorization="Bearer "+token;const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Erro na operação");return d}
function toast(t){const x=$("#toast");x.textContent=t;x.style.display="block";setTimeout(()=>x.style.display="none",2600)}
function toggleMenu(){$("#nav").classList.toggle("open")}
function openModal(html){$("#modalContent").innerHTML=html;$("#modal").classList.remove("hidden")}
function closeModal(){$("#modal").classList.add("hidden")}
function openAuth(mode){
 openModal(`<h2>${mode==="login"?"Entrar no Conect Obra":"Criar sua conta"}</h2>
 <form class="form" onsubmit="${mode==="login"?"login(event)":"register(event)"}">
 ${mode==="register"?`<label>Nome completo<input id="aName" required></label>`:""}
 <label>E-mail<input id="aEmail" type="email" required></label><label>Senha<input id="aPass" type="password" minlength="6" required></label>
 ${mode==="register"?`<div class="row"><label>Perfil<select id="aRole"><option>Cliente</option><option>Profissional</option><option>Empresa</option><option>Fornecedor</option><option>Arquiteto</option><option>Engenheiro</option></select></label><label>Cidade<input id="aCity" placeholder="Ex.: São Paulo"></label></div>`:""}
 <button class="btn" type="submit">${mode==="login"?"Entrar":"Criar conta"}</button>
 </form>
 <p style="text-align:center;color:#66736d;font-size:13px">${mode==="login"?`Ainda não tem conta? <a href="#" onclick="openAuth('register')">Cadastre-se</a>`:`Já possui conta? <a href="#" onclick="openAuth('login')">Entrar</a>`}</p>`);
}
async function login(e){e.preventDefault();try{const d=await api("/api/auth/login",{method:"POST",body:JSON.stringify({email:$("#aEmail").value,password:$("#aPass").value})});token=d.token;me=d.user;localStorage.setItem("co_token",token);closeModal();afterLogin();toast("Bem-vindo ao Conect Obra!")}catch(x){toast(x.message)}}
async function register(e){e.preventDefault();try{const d=await api("/api/auth/register",{method:"POST",body:JSON.stringify({name:$("#aName").value,email:$("#aEmail").value,password:$("#aPass").value,role:$("#aRole").value,city:$("#aCity").value})});token=d.token;me=d.user;localStorage.setItem("co_token",token);closeModal();afterLogin();toast("Conta criada com sucesso!")}catch(x){toast(x.message)}}
async function afterLogin(){renderNav();await loadDashboard();location.hash="#dashboard"}
function renderNav(){const n=$("#nav");n.innerHTML=me?`<a href="#home">Início</a><a href="#obras">Obras</a><a href="#profissionais">Profissionais</a><a href="#dashboard">Minha conta</a><button class="btn" onclick="logout()">Sair</button>`:`<a href="#home">Início</a><a href="#obras">Obras</a><a href="#profissionais">Profissionais</a><a href="#como">Como funciona</a><button class="btn ghost" onclick="openAuth('login')">Entrar</button><button class="btn" onclick="openAuth('register')">Criar conta</button>`}
async function logout(){try{await api("/api/auth/logout",{method:"POST"})}catch{}token="";me=null;localStorage.removeItem("co_token");renderNav();$("#dashboard").classList.add("hidden");location.hash="#home";toast("Você saiu da conta.")}
function requireAuth(fn){if(!me)return openAuth("login");fn()}
async function loadJobs(){try{const q=new URLSearchParams({q:$("#jobSearch")?.value||"",city:$("#citySearch")?.value||"",category:$("#catSearch")?.value||""});const d=await api("/api/jobs?"+q);$("#jobs").innerHTML=d.jobs.length?d.jobs.map(j=>`<article class="job"><span class="tag">${esc(j.category)}</span><h3>${esc(j.title)}</h3><p>${esc(j.description)}</p><div class="job-meta"><span>📍 ${esc(j.city)}</span><b>${esc(j.budget)}</b></div><div class="job-actions"><button class="btn full" onclick="requireAuth(()=>openProposal('${j.id}','${esc(j.title).replace(/'/g,"\\'")}'))">Enviar proposta</button></div></article>`).join(""):`<div class="panel"><h3>Nenhuma obra encontrada</h3><p>Tente outros filtros ou publique uma nova oportunidade.</p></div>`}catch(e){toast(e.message)}}
async function loadProfessionals(){try{const d=await api("/api/professionals?q="+encodeURIComponent($("#proSearch")?.value||""));$("#professionals").innerHTML=d.professionals.length?d.professionals.map(p=>`<article class="pro"><span class="tag">${esc(p.role)}</span><h3>${esc(p.name)}</h3><p>📍 ${esc(p.city||"Brasil")}</p><p>${esc(p.bio||"Profissional disponível para novos projetos.")}</p><button class="btn full" onclick="requireAuth(()=>openContact('${p.id}','${esc(p.name).replace(/'/g,"\\'")}'))">Entrar em contato</button></article>`).join(""):`<div class="panel"><p>Nenhum profissional encontrado.</p></div>`}catch(e){toast(e.message)}}
function openJobModal(){openModal(`<h2>Publicar nova obra</h2><form class="form" onsubmit="createJob(event)"><label>Título<input id="jTitle" required placeholder="Ex.: Reforma completa de apartamento"></label><label>Descrição<textarea id="jDesc" required placeholder="Explique o que precisa ser feito..."></textarea></label><div class="row"><label>Categoria<select id="jCat"><option>Construção</option><option>Reforma</option><option>Elétrica</option><option>Hidráulica</option><option>Pintura</option><option>Arquitetura</option><option>Engenharia</option></select></label><label>Cidade<input id="jCity" required></label></div><div class="row"><label>Orçamento<input id="jBudget" placeholder="Ex.: R$ 30.000"></label><label>Prazo<input id="jDeadline" placeholder="Ex.: 60 dias"></label></div><button class="btn" type="submit">Publicar obra</button></form>`)}
async function createJob(e){e.preventDefault();try{await api("/api/jobs",{method:"POST",body:JSON.stringify({title:$("#jTitle").value,description:$("#jDesc").value,category:$("#jCat").value,city:$("#jCity").value,budget:$("#jBudget").value,deadline:$("#jDeadline").value})});closeModal();loadJobs();loadDashboard();toast("Obra publicada!")}catch(x){toast(x.message)}}
function openProposal(jobId,title){openModal(`<h2>Enviar proposta</h2><p><b>${title}</b></p><form class="form" onsubmit="sendProposal(event,'${jobId}')"><label>Valor da proposta<input id="pAmount" placeholder="Ex.: R$ 18.500"></label><label>Mensagem<textarea id="pMsg" required placeholder="Apresente sua experiência e proposta..."></textarea></label><button class="btn" type="submit">Enviar proposta</button></form>`)}
async function sendProposal(e,id){e.preventDefault();try{await api("/api/jobs/"+id+"/proposals",{method:"POST",body:JSON.stringify({amount:$("#pAmount").value,message:$("#pMsg").value})});closeModal();loadDashboard();toast("Proposta enviada!")}catch(x){toast(x.message)}}
function openContact(id,name){openModal(`<h2>Mensagem para ${name}</h2><form class="form" onsubmit="sendMessage(event,'${id}')"><label>Mensagem<textarea id="mText" required placeholder="Olá, gostaria de conversar sobre um projeto..."></textarea></label><button class="btn" type="submit">Enviar mensagem</button></form>`)}
async function sendMessage(e,id){e.preventDefault();try{await api("/api/messages",{method:"POST",body:JSON.stringify({toUserId:id,text:$("#mText").value})});closeModal();toast("Mensagem enviada!")}catch(x){toast(x.message)}}
async function loadDashboard(){if(!me)return;$("#dashboard").classList.remove("hidden");$("#welcome").textContent="Olá, "+me.name;try{const [mj,rec,sent]=await Promise.all([api("/api/my-jobs"),api("/api/proposals/received"),api("/api/proposals/sent")]);$("#summary").innerHTML=`<div class="item"><b>Perfil:</b> ${esc(me.role)}</div><div class="item"><b>Cidade:</b> ${esc(me.city||"Não informada")}</div><div class="item"><b>Obras publicadas:</b> ${mj.jobs.length}</div><div class="item"><b>Propostas recebidas:</b> ${rec.proposals.length}</div>`;$("#myJobs").innerHTML=mj.jobs.length?mj.jobs.map(j=>`<div class="item"><b>${esc(j.title)}</b><br>📍 ${esc(j.city)} <span class="status">${esc(j.status)}</span></div>`).join(""):"<p>Nenhuma obra publicada.</p>";$("#received").innerHTML=rec.proposals.length?rec.proposals.map(p=>`<div class="item"><b>${esc(p.professionalName)}</b> — ${esc(p.jobTitle)}<br>${esc(p.amount)} <span class="status ${p.status}">${esc(p.status)}</span>${p.status==="pending"?`<br><button class="btn" style="margin-top:8px" onclick="decision('${p.id}','accepted')">Aceitar</button> <button class="btn ghost" style="margin-top:8px" onclick="decision('${p.id}','rejected')">Recusar</button>`:""}</div>`).join(""):"<p>Nenhuma proposta recebida.</p>";$("#sent").innerHTML=sent.proposals.length?sent.proposals.map(p=>`<div class="item"><b>${esc(p.jobTitle)}</b><br>${esc(p.amount)} <span class="status ${p.status}">${esc(p.status)}</span></div>`).join(""):"<p>Nenhuma proposta enviada.</p>"}catch(e){toast(e.message)}}
async function decision(id,status){try{await api("/api/proposals/"+id,{method:"PATCH",body:JSON.stringify({status})});loadDashboard();loadJobs();toast(status==="accepted"?"Proposta aceita!":"Proposta recusada.")}catch(x){toast(x.message)}}
(async function init(){renderNav();if(token){try{me=(await api("/api/me")).user;renderNav();await loadDashboard()}catch{token="";localStorage.removeItem("co_token")}}loadJobs();loadProfessionals()})();
